name: Report Allure

on:
  workflow_run:
    workflows: [E2E Cypress Testes - Sauce Demo]
    types: [completed]

permissions:
  actions: read
  contents: write
  pages: write

jobs:
  report:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'cancelled'

    steps:
      - name: Baixar histórico da branch gh
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Baixar resultados
        uses: actions/download-artifact@v4
        with:
          pattern: allure-*
          path: allure-results
          merge-multiple: true
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Instalar Allure CLI
        run: |
          npm install -g allure-commandline

      - name: Preparar histórico
        run: |
          if [ -d "gh-pages/history" ]; then
            mkdir -p allure-results/history
            cp -R gh-pages/history/*  allure-results/history/
          fi

      - name: Gerar relatório Allure
        run: |
          allure generate allure-results -o allure-history --clean

      - name: Deploy do reporte unificado no Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history
          publish_branch: gh-pages
