name: Report Allure

on:
  workflow_run:
    workflows: [E2E Cypress Testes - Sauce Demo]
    types: [completed]

permissions:
  actions: read
  contents: write
  pages: write

jobs:
  report:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'cancelled'

    steps:
      - name: Baixar histórico da branch gh
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Baixar resultados
        uses: actions/download-artifact@v4
        with:
          pattern: allure-*
          path: allure-results
          merge-multiple: true
          run-id: ${{ github.event.workflow_run.id }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build e Unificação do report
        uses: simple-elf/allure-report-action@v1.11
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 5

      - name: Deploy do reporte unificado no Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history
